# Path: docker-compose.yml
# Purpose: Local development runner for the modular chess stack (frontend, game-svc, engine-svc).
# Usage: docker compose up --build; visit http://localhost:8080

services:
  engine-svc:
    build: ./engine-svc
    environment:
      UCI_ENGINE_PATH: /app/uci_reference_engine.py
      UCI_ENGINE_CMD: "python /app/uci_reference_engine.py"
      ENGINE_READY_TIMEOUT_MS: "5000"
    networks: [chessnet]

  game-svc:
    build: ./game-svc
    environment:
      ENGINE_SVC_URL: http://engine-svc:8001
    depends_on:
      - engine-svc
    ports:
      - "8000:8000"
    networks: [chessnet]

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - game-svc
    networks:
      - chessnet

networks:
  chessnet: {}